services:
  - type: web
    name: voltbharat-cms
    env: node
    region: singapore
    plan: free
    rootDir: cms
    buildCommand: npm install
    startCommand: npm run build && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        sync: false
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_NAME
        value: dgzs47exe
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
